sudo apt-get -y build-dep openssl
sudo apt-get -y build-dep bluetooth
sudo apt-get -y build-dep blueproximity
sudo apt-get -y build-dep btscanner
sudo apt-get -y build-dep hibernate
sudo apt-get -y build-dep vbetool
sudo apt-get -y build-dep uswsusp
sudo apt-get -y build-dep #Uncomment_these_lines_if_you_want_a_fully-fledged_IDE.
sudo apt-get -y build-dep #anjuta
sudo apt-get -y build-dep #anjuta-common
sudo apt-get -y build-dep #anjuta-extras
sudo apt-get -y build-dep asciidoc
sudo apt-get -y build-dep autoconf
sudo apt-get -y build-dep automake
sudo apt-get -y build-dep autotools-dev
sudo apt-get -y build-dep -y build-essential
sudo apt-get -y build-dep cmake
sudo apt-get -y build-dep cgdb
sudo apt-get -y build-dep debhelper
sudo apt-get -y build-dep devhelp-common
sudo apt-get -y build-dep devscripts
sudo apt-get -y build-dep dh-make
sudo apt-get -y build-dep doc-base
sudo apt-get -y build-dep docbook-xml
sudo apt-get -y build-dep docutils-common
sudo apt-get -y build-dep docutils-doc
sudo apt-get -y build-dep doxygen
sudo apt-get -y build-dep dpkg-dev
sudo apt-get -y build-dep gcc
sudo apt-get -y build-dep g++
sudo apt-get -y build-dep medit
sudo apt-get -y build-dep git
sudo apt-get -y build-dep globus-simple-ca
sudo apt-get -y build-dep gperf
sudo apt-get -y build-dep intltool
sudo apt-get -y build-dep libasound2-dev
sudo apt-get -y build-dep libboost-dev
sudo apt-get -y build-dep libboost-chrono-dev
sudo apt-get -y build-dep libboost-filesystem-dev
sudo apt-get -y build-dep libboost-program-options-dev
sudo apt-get -y build-dep libboost-system-dev
sudo apt-get -y build-dep libboost-test-dev
sudo apt-get -y build-dep libboost-thread-dev
sudo apt-get -y build-dep libc6-dev
sudo apt-get -y build-dep libc6-dbg
sudo apt-get -y build-dep libcairo2-dev
sudo apt-get -y build-dep libcurl4-openssl-dev
sudo apt-get -y build-dep libdb-dev
sudo apt-get -y build-dep libev-dev
sudo apt-get -y build-dep libevent-dev
sudo apt-get -y build-dep libgtk2.0-dev
sudo apt-get -y build-dep libimlib2-dev
sudo apt-get -y build-dep libltdl-dev
sudo apt-get -y build-dep libtool
sudo apt-get -y build-dep liblua5.1-dev
sudo apt-get -y build-dep liblua5.2-dev
sudo apt-get -y build-dep libnotify-dev
sudo apt-get -y build-dep libgcrypt11-dev
sudo apt-get -y build-dep libgcrypt20-dev
sudo apt-get -y build-dep libgpg-error-dev
sudo apt-get -y build-dep libotr5
sudo apt-get -y build-dep libotr5-bin
sudo apt-get -y build-dep libotr5-dev
sudo apt-get -y build-dep libpango1.0-dev
sudo apt-get -y build-dep libssl-dev
sudo apt-get -y build-dep libstartup-notification0-dev
sudo apt-get -y build-dep libsodium-dev
sudo apt-get -y build-dep libsodium-dbg
sudo apt-get -y build-dep libstdc++-4.8-dev
sudo apt-get -y build-dep #libtox-dev
sudo apt-get -y build-dep #libtoxcore0
sudo apt-get -y build-dep #libtoxcore-dev
sudo apt-get -y build-dep #libtoxav0
sudo apt-get -y build-dep #libtoxav-dev
sudo apt-get -y build-dep #libtoxencryptsave0
sudo apt-get -y build-dep #libtoxencryptsave-dev
sudo apt-get -y build-dep #libtoxdns0
sudo apt-get -y build-dep #libtoxdns-dev
sudo apt-get -y build-dep libx11-xcb-dev
sudo apt-get -y build-dep libxcb1-dev
sudo apt-get -y build-dep libxcb-image0-dev
sudo apt-get -y build-dep libxcb-icccm4-dev
sudo apt-get -y build-dep libxcb-keysyms1-dev
sudo apt-get -y build-dep libxcb-randr0-dev
sudo apt-get -y build-dep libxcb-shape0-dev
sudo apt-get -y build-dep libxcb-util0-dev
sudo apt-get -y build-dep libxcb-xinerama0-dev
sudo apt-get -y build-dep libxcb-xtest0-dev
sudo apt-get -y build-dep libxcursor-dev
sudo apt-get -y build-dep libxdg-basedir-dev
sudo apt-get -y build-dep libxdo-dev
sudo apt-get -y build-dep libxt-dev
sudo apt-get -y build-dep libiw-dev
sudo apt-get -y build-dep libidl-dev
sudo apt-get -y build-dep mesa-common-dev
sudo apt-get -y build-dep autoconf2.13
sudo apt-get -y build-dep yasm
sudo apt-get -y build-dep python-dev
sudo apt-get -y build-dep libgstreamer0.10-dev
sudo apt-get -y build-dep libgstreamer-plugins-base0.10-dev
sudo apt-get -y build-dep libpulse-dev
sudo apt-get -y build-dep lintian
sudo apt-get -y build-dep lua5.1
sudo apt-get -y build-dep lua5.2
sudo apt-get -y build-dep luadoc
sudo apt-get -y build-dep lua-ldoc
sudo apt-get -y build-dep make
sudo apt-get -y build-dep mercurial
sudo apt-get -y build-dep moreutils
sudo apt-get -y build-dep nodejs
sudo apt-get -y build-dep nodejs-legacy
sudo apt-get -y build-dep p-y builder
sudo apt-get -y build-dep python-rope
sudo apt-get -y build-dep tig
sudo apt-get -y build-dep valac
sudo apt-get -y build-dep valgrind
sudo apt-get -y build-dep xmlto
sudo apt-get -y build-dep zip
sudo apt-get -y build-dep #anoncoind
sudo apt-get -y build-dep #bitcoind
sudo apt-get -y build-dep #litecoind
sudo apt-get -y build-dep #namecoin
sudo apt-get -y build-dep alsa-base
sudo apt-get -y build-dep alsa-tools
sudo apt-get -y build-dep alsa-utils
sudo apt-get -y build-dep alsa-oss
sudo apt-get -y build-dep alsamixergui
sudo apt-get -y build-dep apt-transport-https
sudo apt-get -y build-dep apt-transport-tor
sudo apt-get -y build-dep apt-p2p
sudo apt-get -y build-dep dctrl-tools
sudo apt-get -y build-dep debconf
sudo apt-get -y build-dep debconf-i18n
sudo apt-get -y build-dep debhelper
sudo apt-get -y build-dep debian-archive-keyring
sudo apt-get -y build-dep debian-faq
sudo apt-get -y build-dep debian-keyring
sudo apt-get -y build-dep debianutils
sudo apt-get -y build-dep debootstrap
sudo apt-get -y build-dep debsecan
sudo apt-get -y build-dep debian-security-support
sudo apt-get -y build-dep doc-debian
sudo apt-get -y build-dep dpkg
sudo apt-get -y build-dep dpkg-dev
sudo apt-get -y build-dep dpkg-sig
sudo apt-get -y build-dep gom
sudo apt-get -y build-dep libalsaplayer0
sudo apt-get -y build-dep openrc
sudo apt-get -y build-dep #systemd-shim
sudo apt-get -y build-dep #install_this_for_compatibility_with_systemd_where_necessary
sudo apt-get -y build-dep awesome
sudo apt-get -y build-dep awesome-extra
sudo apt-get -y build-dep #awesome-lightdm-session
sudo apt-get -y build-dep compton
sudo apt-get -y build-dep conky-std
sudo apt-get -y build-dep dialog
sudo apt-get -y build-dep network-manager
sudo apt-get -y build-dep #modem-manager
sudo apt-get -y build-dep mc
sudo apt-get -y build-dep lightdm
sudo apt-get -y build-dep lightdm-vala
sudo apt-get -y build-dep lightdm-gtk-greeter
sudo apt-get -y build-dep pcmanfm
sudo apt-get -y build-dep #svirfneblin-panel
sudo apt-get -y build-dep #Right_now_these_are_just_included_in_etc/skel
sudo apt-get -y build-dep #svirfneblin-*
sudo apt-get -y build-dep #Right_now_these_are_just_included_in_etc/skel
sudo apt-get -y build-dep terminator
sudo apt-get -y build-dep x11-apps
sudo apt-get -y build-dep #xcalc
sudo apt-get -y build-dep wcalc
sudo apt-get -y build-dep xterm
sudo apt-get -y build-dep #xdialog
sudo apt-get -y build-dep #Uncomment_these_if_you_want_to_use_a_GTK_Based_Office_Suite.
sudo apt-get -y build-dep #abiword
sudo apt-get -y build-dep #abiword-common
sudo apt-get -y build-dep #abiword-plugin-grammar
sudo apt-get -y build-dep #abiword-plugin-mathview
sudo apt-get -y build-dep #caca-utils
sudo apt-get -y build-dep #dia
sudo apt-get -y build-dep #dia-common
sudo apt-get -y build-dep #dia-libs
sudo apt-get -y build-dep #dia-shapes
sudo apt-get -y build-dep #gnumeric
sudo apt-get -y build-dep #gnumeric-common
sudo apt-get -y build-dep #gnumeric-doc
sudo apt-get -y build-dep imagemagick
sudo apt-get -y build-dep imagemagick-6.q16
sudo apt-get -y build-dep imagemagick-common
sudo apt-get -y build-dep markdown
sudo apt-get -y build-dep pinta
sudo apt-get -y build-dep iceweasel-l10n-en-gb
sudo apt-get -y build-dep icedove-l10n-en-gb
sudo apt-get -y build-dep libreoffice-l10n-en-gb
sudo apt-get -y build-dep iceweasel-l10n-es-es
sudo apt-get -y build-dep icedove-l10n-es-es
sudo apt-get -y build-dep libreoffice-l10n-es
sudo apt-get -y build-dep iceweasel-l10n-eu
sudo apt-get -y build-dep icedove-l10n-eu
sudo apt-get -y build-dep openoffice.org-l10n-eu
sudo apt-get -y build-dep hunspell-eu-es
sudo apt-get -y build-dep hydra
sudo apt-get -y build-dep john
sudo apt-get -y build-dep sqlmap
sudo apt-get -y build-dep ophcrack
sudo apt-get -y build-dep sslscan
sudo apt-get -y build-dep sslsniff
sudo apt-get -y build-dep sslstrip
sudo apt-get -y build-dep thc-ipv6
sudo apt-get -y build-dep wireshark
sudo apt-get -y build-dep yersinia
sudo apt-get -y build-dep fdroidserver
sudo apt-get -y build-dep crawl-common
sudo apt-get -y build-dep crawl-tiles
sudo apt-get -y build-dep crawl-tiles-data
sudo apt-get -y build-dep freeciv-client-sdl
sudo apt-get -y build-dep wesnoth
sudo apt-get -y build-dep apparmor
sudo apt-get -y build-dep apparmor-docs
sudo apt-get -y build-dep apparmor-profiles
sudo apt-get -y build-dep apparmor-utils
sudo apt-get -y build-dep ferm
sudo apt-get -y build-dep fireblock
sudo apt-get -y build-dep hidblock
sudo apt-get -y build-dep nufw
sudo apt-get -y build-dep rkhunter
sudo apt-get -y build-dep i2p
sudo apt-get -y build-dep i2p-keyring
sudo apt-get -y build-dep i2p-router
sudo apt-get -y build-dep killyourtv-keyring
sudo apt-get -y build-dep lynx-cur
sudo apt-get -y build-dep ncftp
sudo apt-get -y build-dep uzbl
sudo apt-get -y build-dep xombrero
sudo apt-get -y build-dep iceweasel-l10n-it
sudo apt-get -y build-dep icedove-l10n-it
sudo apt-get -y build-dep libreoffice-l10n-it
sudo apt-get -y build-dep live-boot
sudo apt-get -y build-dep live-boot-doc
sudo apt-get -y build-dep live--y build
sudo apt-get -y build-dep live-config
sudo apt-get -y build-dep live-config-doc
sudo apt-get -y build-dep live-config-sysvinit
sudo apt-get -y build-dep live-manual-html
sudo apt-get -y build-dep cmus
sudo apt-get -y build-dep imagemagick
sudo apt-get -y build-dep quodlibet
sudo apt-get -y build-dep vlc
sudo apt-get -y build-dep alfred
sudo apt-get -y build-dep batctl
sudo apt-get -y build-dep curl
sudo apt-get -y build-dep horst
sudo apt-get -y build-dep iftop
sudo apt-get -y build-dep iptraf-ng
sudo apt-get -y build-dep #joker
sudo apt-get -y build-dep netcat
sudo apt-get -y build-dep nmap
sudo apt-get -y build-dep #rtorrent
sudo apt-get -y build-dep sntop
sudo apt-get -y build-dep wget
sudo apt-get -y build-dep youtube-dl
sudo apt-get -y build-dep apg
sudo apt-get -y build-dep bleachbit
sudo apt-get -y build-dep blueproximity
sudo apt-get -y build-dep gnupg
sudo apt-get -y build-dep gnupg-agent
sudo apt-get -y build-dep gnupg2
sudo apt-get -y build-dep macchanger
sudo apt-get -y build-dep mat
sudo apt-get -y build-dep #parcimonie
sudo apt-get -y build-dep secure-delete
sudo apt-get -y build-dep alpine
sudo apt-get -y build-dep irssi
sudo apt-get -y build-dep mumble
sudo apt-get -y build-dep mutt
sudo apt-get -y build-dep profanity
sudo apt-get -y build-dep toxic
sudo apt-get -y build-dep twidge
sudo apt-get -y build-dep #twister
sudo apt-get -y build-dep #tox-bootstrapd
sudo apt-get -y build-dep bumblebee
sudo apt-get -y build-dep firmware-linux-free
sudo apt-get -y build-dep laptop-mode-tools
sudo apt-get -y build-dep linux-image-amd64
sudo apt-get -y build-dep primus
sudo apt-get -y build-dep sudo
sudo apt-get -y build-dep syslinux-common
sudo apt-get -y build-dep syslinux-efi
sudo apt-get -y build-dep user-setup
sudo apt-get -y build-dep deb.torproject.org-keyring
sudo apt-get -y build-dep privoxy
sudo apt-get -y build-dep tor
sudo apt-get -y build-dep tor-arm
sudo apt-get -y build-dep tor-geoipdb
sudo apt-get -y build-dep torsocks
sudo apt-get -y build-dep lshw
sudo apt-get -y build-dep htop
sudo apt-get -y build-dep usbutils
sudo apt-get -y build-dep aircrack-ng
sudo apt-get -y build-dep reaver
sudo apt-get -y build-dep wifite
