#! /bin/sh

if [ -f /usr/bin/srm ]; then
	alias rm=/usr/bin/srm
fi

if [ -f "$1" ]; then
	TEMP=$(cat "$1" | grep "work_dir")
	export $(echo "$TEMP" | tr -d " ")
	mv -v "$work_dir""cert.pem" "$work_dir""cert.pem.old" 2> /dev/null
else
	TEMP=$(cat "$HOME/.xombrero.conf" | grep "work_dir")
	export $(echo "$TEMP" | tr -d " ")
	if [ -z "$work_dir" ]; then
		work_dir="$HOME/.xombrero/"
	fi
	if [ -d "$work_dir" ]; then
		mv -v "$HOME/.xombrero/cert.pem" "$HOME/.xombrero/cert.pem.old" 2> /dev/null
	else
		mkdir $work_dir -p
	fi
fi

SYSTEM_CERTS=$(find /etc/ssl/certs -name *.pem 2> /dev/null)
for pem in $SYSTEM_CERTS; do
	if [ "$1" != "q" ]; then
		echo "libssl provided a certificate, $pem."
		echo "Should I add this to your certificates?"
		if [ "$1" = "v" ]; then
			cat "$pem"
			echo "Review Certificate and press Enter to continue"
			if [ $ANSWER = "yes" ]; then
				cat "$pem" >> "$work_dir""cert.pem"		
			fi
		else
			if [ $ANSWER = "yes" ]; then
				cat "$pem" >> "$work_dir""cert.pem"		
			fi
		fi
	else
		cat "$pem" >> "$work_dir""cert.pem"
	fi
done

TOR_CERT=$(find / -name torproject.pem 2> /dev/null)
TOR_CERT_CAT=$(echo "$TOR_CERT" | grep -v "$HOME/Projects")
if [ "$1" != "q" ]; then
	echo "Possible Tor Project Certificate found in $TOR_CERT_CAT."
	echo "Should I add this to your certificates?"
	if [ "$1" = "v" ]; then
		cat "$TOR_CERT_CAT"
		echo "Review Certificate and press Enter to continue"
		if [ $ANSWER = "yes" ]; then
			cat "$TOR_CERT_CAT" >> "$work_dir""cert.pem"		
		fi
	else
		cat "$TOR_CERT_CAT" >> "$work_dir""cert.pem"		
	fi
else
	cat "$TOR_CERT_CAT" >> "$work_dir""cert.pem"
fi

cache(){
	if [ "$1" = "v" ] || [ "$1" = "q" ]; then
		echo -n " "
	elif [ "$1" = "c" ]; then
		DATE=$(date +%Y%m%d)
		if [ -f "$2" ]; then
			TEMP=$(cat "$2" | grep "work_dir")
			export $(echo "$TEMP" | tr -d " " )
			mv -v "$work_dir/cert.pem.old" "$work_dir/cert_cache/cert$DATE.pem" 2> /dev/null
		elif [ -d "$work_dir" ]; then
			mv -v "$work_dir/cert.pem.old" "$work_dir/cert_cache/cert$DATE.pem" 2> /dev/null
		fi
	else
		echo -n " "
	fi
}

custom_file(){
	if [ -f "$1" ]; then
		TEMP=$(cat "$1" | grep "ssl_ca_file")
		export $(echo $TEMP | tr -d " " )
		if [ -z "$ssl_ca_file" ]; then
			TEMP=$(cat "$1" | grep "work_dir")
			export $(echo "$TEMP" | tr -d " " )
			if [ -f "$ssl_ca_file" ]; then
				echo "Existing TLS Certificates found."
			else
				if [ -d "$work_dir" ]; then
					echo "ssl_ca_file	 = $work_dir/cert.pem" >> "$1.conf"
				fi
			fi
			cache "$2" "$1"
			clear_cache "$2" "$1"
		fi
	fi
}

clear_cache(){
	if [ "$1" = "cc" ]; then
		if [ -f "$2" ]; then
			TEMP=$(cat "$2" | grep "work_dir")
			export $(echo "$TEMP" | tr -d " " )
		fi
		if [ -d "$work_dir/cert_cache" ]; then
			rm -v "$work_dir/cert_cache/*" 2> /dev/null
		fi
	fi
}

FILE_LIST="$HOME/.xombrero.conf 
$HOME/.insecure.conf 
$1 
$2 
$3 "

for f in $FILE_LIST; do
	if [ -z "$1" ]; then
		custom_file "$f" "$1"
	elif [ -z "$2" ]; then
		custom_file "$f" "$2"
	elif [ -z "$3" ]; then
		custom_file "$f" "$3"
	fi
done

rm -v "$work_dir""cert.pem.old" 2> /dev/null