# Generated by ferm 2.2 on Fri Feb 12 07:59:40 2016
*filter
:FORWARD ACCEPT [0:0]
:INPUT DROP [0:0]
:OUTPUT DROP [0:0]
:lan - [0:0]
-A FORWARD --jump ACCEPT
-A INPUT --match state --state INVALID --jump DROP
-A INPUT --match state --state ESTABLISHED,RELATED --jump ACCEPT
-A INPUT --in-interface lo --jump ACCEPT
-A INPUT --protocol tcp --dport 4433 --jump ACCEPT
-A INPUT --protocol tcp --dport 4434 --jump ACCEPT
-A INPUT --protocol tcp --dport 28333 --jump ACCEPT
-A INPUT --protocol tcp --dport 29333 --jump ACCEPT
-A INPUT --protocol udp --dport 29333 --jump ACCEPT
-A INPUT --match owner --uid-owner i2psvc --jump ACCEPT
-A INPUT --match limit --limit 3/min --limit-burst 10 --jump LOG --log-prefix "INPUT-rejected: " --log-level debug
-A INPUT --jump REJECT
-A OUTPUT --match owner --uid-owner debian-tor --jump ACCEPT
-A OUTPUT --match owner --uid-owner i2psvc --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6881 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6882 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6883 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6885 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6886 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6887 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6888 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6889 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 28333 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 29333 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 51413 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6881 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6882 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6883 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6885 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6886 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6887 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6888 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6889 --jump ACCEPT
-A OUTPUT --protocol udp --dport 28333 --jump ACCEPT
-A OUTPUT --protocol udp --dport 29333 --jump ACCEPT
-A OUTPUT --protocol udp --dport 51413 --jump ACCEPT
-A OUTPUT --out-interface lo --jump ACCEPT
-A lan --protocol tcp --dport domain --jump REJECT
-A lan --protocol udp --dport domain --jump REJECT
COMMIT
# Generated by ferm 2.2 on Fri Feb 12 07:59:40 2016
*nat
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]
-A OUTPUT --destination 127.192.0.0/10 --protocol tcp --jump REDIRECT --to-ports 9040
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 53 --jump REDIRECT --to-ports 5353
COMMIT
*filter
:FORWARD ACCEPT [0:0]
:INPUT DROP [0:0]
:OUTPUT DROP [0:0]
:lan - [0:0]
-A FORWARD --jump ACCEPT
-A INPUT --match state --state INVALID --jump DROP
-A INPUT --match state --state ESTABLISHED,RELATED --jump ACCEPT
-A INPUT --in-interface lo --jump ACCEPT
-A INPUT --protocol tcp --dport 4433 --jump ACCEPT
-A INPUT --protocol tcp --dport 4434 --jump ACCEPT
-A INPUT --protocol tcp --dport 28333 --jump ACCEPT
-A INPUT --protocol tcp --dport 29333 --jump ACCEPT
-A INPUT --protocol udp --dport 29333 --jump ACCEPT
-A INPUT --match owner --uid-owner i2psvc --jump ACCEPT
-A INPUT --match limit --limit 3/min --limit-burst 10 --jump LOG --log-prefix "INPUT-rejected: " --log-level debug
-A INPUT --jump REJECT
-A OUTPUT --match owner --uid-owner debian-tor --jump ACCEPT
-A OUTPUT --match owner --uid-owner i2psvc --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --syn --dport 9050 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --syn --match multiport --destination-ports 5353,9040,9050,9051,8118,9061,9062,9150,8123 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --syn --match multiport --destination-ports 2827,4444,4445,6668,7656,7657,7658,7659,7660,8998 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 53 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 5353 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --syn --dport 8118 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --syn --dport 8123 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6881 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6882 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6883 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6885 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6886 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6887 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6888 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 6889 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 28333 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 29333 --jump ACCEPT
-A OUTPUT --protocol tcp --dport 51413 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6881 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6882 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6883 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6885 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6886 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6887 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6888 --jump ACCEPT
-A OUTPUT --protocol udp --dport 6889 --jump ACCEPT
-A OUTPUT --protocol udp --dport 28333 --jump ACCEPT
-A OUTPUT --protocol udp --dport 29333 --jump ACCEPT
-A OUTPUT --protocol udp --dport 51413 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --syn --dport 631 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --syn --dport 6136 --jump ACCEPT
-A OUTPUT --destination 10.0.0.0/8 --jump lan
-A OUTPUT --destination 172.16.0.0/12 --jump lan
-A OUTPUT --destination 192.168.0.0/16 --jump lan
-A OUTPUT --destination 127.0.0.1 --protocol tcp --dport 28332 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 28332 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 1900 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 29333 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 60177 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --dport 55166 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --dport 55167 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --dport 55526 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --dport 55177 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol tcp --dport 55184 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 55166 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 55167 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 55526 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 55177 --jump ACCEPT
-A OUTPUT --destination 127.0.0.1 --protocol udp --dport 55184 --jump ACCEPT
-A OUTPUT --out-interface lo --jump ACCEPT
-A lan --protocol tcp --dport domain --jump REJECT
-A lan --protocol udp --dport domain --jump REJECT
COMMIT
