#!/bin/bash -e
set -e

if [ "$1" = "configure" -o "$1" = "abort-upgrade" ]; then
    # Alternatives for the background
    while read background priority; do
        update-alternatives --install \
            /usr/share/images/desktop-base/desktop-background \
            desktop-background \
            /usr/share/images/freepto-graphics/$background $priority
    done << EOF
freepto-wallpaper_1024x768.png 80
EOF


	# Set up an alternative for the XML version of the background
	# (for GNOME)
	update-alternatives --install \
		/usr/share/images/freepto-graphics/desktop-background.xml \
		desktop-background.xml \
		/usr/share/images/freepto-graphics/freepto-desktop.xml 20
fi
