#!/bin/sh -e
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    # remove background alternatives
    for background in \
	    freepto_1024x768.png \
          ; do
        update-alternatives --remove desktop-background /usr/share/images/freepto-graphics/$background
    done
    update-alternatives --remove desktop-background.xml /usr/share/images/freepto-graphics/freepto-desktop.xml

fi
